services:
  backend:
    container_name: web
    image: backend:latest
    build:
      context: ./backend
    environment:
      MOST_COMMON_NOUNS_COUNT: 50
      SIMILARITY_THRESHOLD: 0.5

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"